name: Flow_Tests

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r req.txt
    - name: Set up iperf3
      run: |
        sudo apt-get update
        sudo apt-get install iperf3
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8
    - name: Pytest run
      run: |
        pip install pytest
        pytest tests
  